// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztksesbncfpyzwwyllkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a3Nlc2JuY2ZweXp3d3lsbGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzY3NjAsImV4cCI6MjA1MjU1Mjc2MH0.bDaW4TuACW_px7m_0lZDFEUb3japQsBGbCKXHEzbjaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);